version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.2.0

workflows:
  on-commit:
    jobs:
      - shellcheck/check:
          dir: ./scripts
          exclude: SC2148
          filters:
            branches:
              ignore: master
